#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

source activate ipykernel_py2

jupyter nbextension install --py --sys-prefix widgetsnbextension && \
jupyter nbextension enable --py widgetsnbextension --sys-prefix

pip install pythreejs==0.3.1
jupyter nbextension install --py --sys-prefix pythreejs && \
jupyter nbextension enable --py pythreejs --sys-prefix

mkdir ~/.ipython/profile_default/startup
cp ~/resources/cqjupyter.py ~/.ipython/profile_default/startup